/*
   Login action types
*/

export const SET_OTP_RESPONSE = "SET_OTP_RESPONSE";
export const SET_CONFIRM_OTP_RESPONSE = "SET_CONFIRM_OTP_RESPONSE";
export const SET_LOGIN_RESPONSE = "SET_LOGIN_RESPONSE";

/*
   Util action types
*/

export const SET_CURRENT_USER_TOKEN = "SET_CURRENT_USER_TOKEN";
export const SET_CURRENT_USER_MOBILE_NUMBER = "SET_CURRENT_USER_MOBILE_NUMBER";
export const SET_MINI_STATEMENT = "SET_MINI_STATEMENT";
export const UPDATE_USER_EMAIL_ID = "UPDATE_USER_EMAIL_ID";
export const UPDATE_APP_LANGUAGE = "UPDATE_APP_LANGUAGE";
export const UPDATE_NOTIFICATION_ALLOWED = "UPDATE_NOTIFICATION_ALLOWED";
export const UPDATE_USER_KYC = "UPDATE_USER_KYC";
export const UPDATE_MPIN = "UPDATE_MPIN";
export const SET_MPIN = "SET_MPIN";

/*
   UserData action types
*/

export const UPDATE_CURRENT_USER_DETAILS = "UPDATE_CURRENT_USER_DETAILS";
export const SET_CURRENT_USER_DETAIL = "SET_CURRENT_USER_DETAIL";
export const SET_CURRENT_USER_CARD_LIST = "SET_CURRENT_USER_CARD_LIST";
export const SET_SELECTED_CARD_DETAILS = "SET_SELECTED_CARD_DETAILS";
export const SET_CURRENT_USER_CARDS_BALANCE = "SET_CURRENT_USER_CARDS_BALANCE";
export const SET_CURRENT_USER_CARD_DETAILS = "SET_CURRENT_USER_CARD_DETAILS";
export const SET_CURRENT_USER_CARD_BALANCE = "SET_CURRENT_USER_CARD_BALANCE";
export const SET_CURRENT_USER_CARD_HOTLIST_FREEZE = "SET_CURRENT_USER_CARD_HOTLIST_FREEZE";
export const SET_BALANCE_AND_LIMIT_DETAILS = "SET_BALANCE_AND_LIMIT_DETAILS";